USE sakila;

# 1 List the number of films per category

SELECT * FROM film;
SELECT * FROM film_category;
SELECT * FROM category;

SELECT c.name AS category, COUNT(f.title)
FROM category AS c
LEFT JOIN film_category AS fc
ON c.category_id = fc.category_id
LEFT JOIN film AS f
ON fc.film_id = f.film_id
GROUP BY category;

# 2 Retrieve the store ID, city, and country for each store.

SELECT * FROM store;
SELECT * FROM address;
SELECT * FROM city;
SELECT * FROM country;

SELECT s.store_id, c.city, co.country
FROM store AS s
LEFT JOIN address AS a
ON s.address_id = a.address_id
LEFT JOIN city AS c
ON a.city_id = c.city_id
LEFT JOIN country AS co
ON c.country_id = co.country_id;

# 3 Calculate the total revenue generated by each store in dollars.

SELECT * FROM store;
SELECT * FROM staff;
SELECT * FROM payment;

SELECT sto.store_id, SUM(p.amount) AS total_revenue
FROM store AS sto
LEFT JOIN staff AS sta
ON sto.store_id = sta.staff_id
LEFT JOIN payment AS p
ON sta.staff_id = p.staff_id
GROUP BY sto.store_id;

# 4 Determine the average running time of films for each category.

SELECT * FROM film;
SELECT * FROM film_category;
SELECT * FROM category;

SELECT name AS category, AVG(f.length) as avg_length
FROM category as c
LEFT JOIN film_category as fc
ON c.category_id = fc.category_id
LEFT JOIN film as f
ON fc.film_id = f.film_id
GROUP BY category;

# 5 Identify the film categories with the longest average running time.

SELECT c.name AS category, AVG(f.length) as avg_length
FROM category as c
LEFT JOIN film_category as fc
ON c.category_id = fc.category_id
LEFT JOIN film as f
ON fc.film_id = f.film_id
GROUP BY c.name
ORDER BY avg_length DESC
LIMIT 1;

# 6 Display the top 10 most frequently rented movies in descending order.

SELECT * FROM film;
SELECT * FROM inventory;
SELECT * FROM rental;

SELECT f.title, COUNT(rental_id) AS rental_count 
FROM film AS f
LEFT JOIN inventory AS i
ON f.film_id = i.film_id
LEFT JOIN rental AS r
ON i.inventory_id = r.inventory_id
GROUP BY f.title
ORDER BY rental_count DESC
LIMIT 10;

# 7 Determine if "Academy Dinosaur" can be rented from Store 1.

SELECT * FROM film;
SELECT * FROM inventory;
SELECT * FROM store;
SELECT * FROM rental;

SELECT f.title, s.store_id
FROM film as f
LEFT JOIN inventory AS i
	ON f.film_id = i.film_id
LEFT JOIN store AS s
	ON i.store_id = s.store_id
WHERE f.title = "Academy Dinosaur" 
	AND s.store_id = 1;
    

